#!/bin/bash
set -e

function runTest() {
    echo "Running integration tests defined in $1"
    echo "============================================================"
    if ! docker compose -f "$1" up --build --quiet-pull --always-recreate-deps --force-recreate --abort-on-container-exit --remove-orphans --renew-anon-volumes --exit-code-from sut; then
        docker compose -f "$1" down
        echo "$1 failed. To run this test in isolation:" 1>&2
        echo "" 1>&2
        echo "    ./test $1" 1>&2
        exit 1
    else
        docker compose -f "$1" down
        echo "$1 passed"
        echo ""
    fi
}

if [ "${IN_CONTAINER}" != "true" ]; then
  . $(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.devcontainer/common.sh

    # Don't write to the local cache if we're running locally or on a PR build
    if [ -n "$CODESPACE_NAME" ] || ( [ -n "$GITHUB_REF_NAME" ] && [ "$GITHUB_REF_NAME" != "main" ] ) ; then
        docker buildx bake -f docker-compose.build.yml --load --set *.cache-to=''
    else
        docker buildx bake -f docker-compose.build.yml --load
    fi
    docker tag registry:5000/shell:latest casedhub-shell-test

    if [ -n "$1" ]; then
        runTest "$1"
    else
        for f in tests/integration/*/docker-compose.test.yml; do
            runTest "$f"
        done
    fi
    echo "All integration tests passed!"
    exit
fi

SECONDS=0

echo "Running $SUITE tests..."
bash tests/integration/test-startup.sh
bash tests/integration/$SUITE/test

if [ "$SECONDS" -gt "30" ]; then
    echo "$SUITE suite took ${SECONDS}s to run, longer than our 30s goal" 2>&1
    exit 1
else
    echo "$SUITE suite passed in ${SECONDS}s"
fi


