#!/bin/bash
set -e

. $(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../common.sh

mkdir -p $(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../../tmp/buildx

echo "Building..."
docker buildx bake -f docker-compose.build.yml "$@"
