#!/bin/bash
set -e

if [ -f tmp/kubeconfig.yaml ]; then
  kubectl apply -f .devcontainer/k8s/local-path-storage.yml > /dev/null || true
  until helm upgrade \
    --install \
    ingress-nginx \
    ingress-nginx \
    --repo https://kubernetes.github.io/ingress-nginx \
    --namespace ingress-nginx \
    --create-namespace \
    --set=controller.ingressClassResource.default=true \
    --set=controller.watchIngressWithoutClass=true \
    --set controller.config.use-forwarded-headers=true \
    --set controller.config.enable-access-log-for-default-backend=true \
    --set controller.config.ssl-protocols='TLSv1 TLSv1.1 TLSv1.2 TLSv1.3' \
    --set controller.config.ssl-early-data=false \
    > /dev/null; do
    if [ $SECONDS -gt 60 ]; then
      exit 1
    fi
    echo "retrying..."
    sleep 10
  done
fi
