#!/bin/bash
set -e

. $(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../common.sh

docker buildx install

: ${REGISTRY:=localhost:5000}
export REGISTRY
export DOCKER_BUILDKIT=1
export BUILDKIT_PROGRESS=plain

printf "Restarting registry container..."
docker restart $(devcontainer_name registry)

waitForRegistry registry:5000

# buildx can't seem to reach registry:5000, so we proxy it through socat
pkill -f registry:5000 || true
socat TCP-LISTEN:5000,fork,reuseaddr TCP:registry:5000 &
socat_pid=$!

trap 'kill $socat_pid 2>/dev/null' EXIT

waitForRegistry localhost:5000 busybox

echo "Pushing..."
timeout 300 docker compose -f .devcontainer/docker-compose.build.yml push