apiVersion: v2
name: cased-shell
icon: https://github.com/cased.png
type: application
home: https://cased.com
# Versioning
#
# See https://helm.sh/docs/topics/charts/#charts-and-versioning and
# ../README.md for requirements.
#
version: '3.0.0-alpha.7'
appVersion: '3.0.0'
maintainers:
  # Required by chart-testing to be a GitHub org slug
  - name: Cased
    email: eng@cased.com
    url: https://cased.com
dependencies:
  - name: postgresql
    version: '12.1.0'
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
  - name: vault
    version: '0.22.1'
    repository: 'https://helm.releases.hashicorp.com'
    condition: vault.enabled
