name: Build Docker Image - Required

env:
  DOCKER_BUILDKIT: '1'
  BUILDKIT_PROGRESS: 'plain'

concurrency:
  group: ${{ github.event_name }}-${{ github.event.action }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - gh-readonly-queue/main/*
    # Build and push cased/shell:vX.X.X images on push to tags matching vX.X.X
    tags:
      - v*
  # Build and push images on PRs with the docker:pr-image label
  pull_request:
    types:
      - opened
      - labeled
      - synchronize
  # Support manual builds
  workflow_dispatch:
  schedule:
    # Keep the build cache warm by running a weekly build on the default branch
    # https://github.com/actions/cache#cache-limits
    # > Caches that are not accessed within the last week will also be evicted.
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'opened' ||
      github.event.action == 'synchronize' ||
      github.event_name == 'push' ||
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      ( github.event.action == 'labeled' && github.event.label.name == 'docker:pr-image')
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: shell
            context: ./
            dockerfile: Dockerfile
            vuln-type: os,library
            platforms: linux/amd64
          - name: sshd-demo
            context: .devcontainer/sshd
            dockerfile: .devcontainer/sshd/Dockerfile
            vuln-type: os,library
            platforms: linux/amd64
          - name: shell-devcontainer
            context: ./
            dockerfile: .devcontainer/Dockerfile
            # TODO
            # vuln-type: os,library
            vuln-type: os
            platforms: linux/amd64
            args: |
              NODE_VERSION=lts/*

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: docker_meta
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ github.token }}
          images: |
            ghcr.io/cased/${{ matrix.image.name }}
          tags: |
            type=raw,enable=${{ endsWith(github.ref, github.event.repository.default_branch) && matrix.image.name == 'shell' }},value=unstable
            type=raw,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }},value=${{ github.event.repository.default_branch }}
            type=raw,enable=${{ contains(github.event.pull_request.labels.*.name, 'docker:pr-image') }},value=pr-${{ github.event.pull_request.number }}
            type=semver,pattern=v{{version}}
          labels: |
            org.opencontainers.image.title=Cased Shell
            org.opencontainers.image.description=The terminal for teams

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: scan dockerfile
        uses: aquasecurity/trivy-action@0.8.0
        with:
          scan-type: 'config'
          scan-ref: ${{ matrix.image.dockerfile }}
          trivyignores: ${{ matrix.image.context }}/.trivyignore

      - name: build and cache
        uses: docker/build-push-action@v3
        timeout-minutes: 120
        continue-on-error: true
        id: build
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          platforms: ${{ matrix.image.platforms }}
          build-args: |
            ${{ matrix.image.args }}
            GIT_SHA=${{ github.sha }}
          pull: true
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ghcr.io/cased/${{ matrix.image.name }}:${{ github.sha }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: |
            type=registry,ref=ghcr.io/cased/${{ matrix.image.name }}:${{ github.event.repository.default_branch }}
            type=registry,ref=ghcr.io/cased/${{ matrix.image.name }}:${{ contains(github.event.pull_request.labels.*.name, 'docker:pr-image') && format('pr-{0}', github.event.number) || github.event.repository.default_branch }}
            type=registry,ref=ghcr.io/cased/${{ matrix.image.name }}-cache:${{ github.event.repository.default_branch }}
            type=registry,ref=ghcr.io/cased/${{ matrix.image.name }}-cache:${{ contains(github.event.pull_request.labels.*.name, 'docker:pr-image') && format('pr-{0}', github.event.number) || github.event.repository.default_branch }}
            type=gha,scope=${{ matrix.image.name }}-${{ github.event.repository.default_branch }}
            type=gha,scope=${{ matrix.image.name }}-${{ github.ref_name }}
          cache-to: |
            type=gha,mode=max,scope=${{ matrix.image.name }}-${{ github.ref_name }}

      - name: build without cache
        uses: docker/build-push-action@v3
        if: steps.build.outcome == 'failure'
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          platforms: ${{ matrix.image.platforms }}
          build-args: |
            ${{ matrix.image.args }}
            GIT_SHA=${{ github.sha }}
          pull: true
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ghcr.io/cased/${{ matrix.image.name }}:${{ github.sha }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: |
            type=registry,ref=ghcr.io/cased/${{ matrix.image.name }}:${{ github.event.repository.default_branch }}
            type=registry,ref=ghcr.io/cased/${{ matrix.image.name }}:${{ contains(github.event.pull_request.labels.*.name, 'docker:pr-image') && format('pr-{0}', github.event.number) || github.event.repository.default_branch }}
            type=registry,ref=ghcr.io/cased/${{ matrix.image.name }}-cache:${{ github.event.repository.default_branch }}
            type=registry,ref=ghcr.io/cased/${{ matrix.image.name }}-cache:${{ contains(github.event.pull_request.labels.*.name, 'docker:pr-image') && format('pr-{0}', github.event.number) || github.event.repository.default_branch }}
            type=gha,scope=${{ matrix.image.name }}-${{ github.event.repository.default_branch }}
            type=gha,scope=${{ matrix.image.name }}-${{ github.ref_name }}

      - name: push
        if: startsWith(github.ref, 'refs/tags/') || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || contains(github.event.pull_request.labels.*.name, 'docker:pr-image')
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          platforms: ${{ matrix.image.platforms }}
          build-args: |
            ${{ matrix.image.args }}
            GIT_SHA=${{ github.sha }}
          pull: true
          # This build is run on a schedule to keep the cache stores it
          # publishes to warm. Pushing the resulting images causes unnecessary
          # churn in our image registry, so we don't push them in that case. We
          # continue to push images in all other cases covered by the `if`
          # condition of this step.
          push: ${{ github.event_name != 'schedule' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: |
            type=registry,ref=ghcr.io/cased/${{ matrix.image.name }}:${{ github.event.repository.default_branch }}
            type=registry,ref=ghcr.io/cased/${{ matrix.image.name }}:${{ contains(github.event.pull_request.labels.*.name, 'docker:pr-image') && format('pr-{0}', github.event.number) || github.event.repository.default_branch }}
            type=registry,ref=ghcr.io/cased/${{ matrix.image.name }}-cache:${{ github.event.repository.default_branch }}
            type=registry,ref=ghcr.io/cased/${{ matrix.image.name }}-cache:${{ contains(github.event.pull_request.labels.*.name, 'docker:pr-image') && format('pr-{0}', github.event.number) || github.event.repository.default_branch }}
            type=gha,scope=${{ matrix.image.name }}-${{ github.event.repository.default_branch }}
            type=gha,scope=${{ matrix.image.name }}-${{ github.ref_name }}
          cache-to: |
            type=registry,ref=ghcr.io/cased/${{ matrix.image.name }}-cache:${{ github.event.number == 0 && (startsWith(github.ref, 'refs/tags/') && 'latest' || github.event.repository.default_branch) || format('pr-{0}', github.event.number) }},mode=max
